services:
  - type: web
    name: python-backend
    runtime: docker
    dockerfilePath: ./backend/python/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: go-price-service
    runtime: docker
    dockerfilePath: ./backend/go/Dockerfile
    plan: starter
    envVars:
      - key: PORT
        value: 9000

  - type: web
    name: frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: starter
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHON_BACKEND_URL
        fromService:
          type: web
          name: python-backend
          property: host
      - key: GO_SERVICE_URL
        fromService:
          type: web
          name: go-price-service
          property: host
