services:
  python-backend:
    build: ./backend/python
    container_name: veg-python
    ports:
      - "8000:8000"
    restart: unless-stopped

  go-price-service:
    build: ./backend/go
    container_name: veg-go
    ports:
      - "9000:9000"
    restart: unless-stopped

  frontend:
    image: node:20-alpine
    container_name: veg-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npx serve -s /app -l 8080
    ports:
      - "8080:8080"
    depends_on:
      - python-backend
      - go-price-service
    restart: unless-stopped
